-- Limit, Offset & Fetch

-- Clause to get a subset of rows generated by a query

-- PostgreSQL LIMIT is an optional clause of the SELECT statement that constrains the number of rows returned by the query.

-- In case you want to skip a number of rows before returning the row_count rows, you use OFFSET clause placed after the LIMIT

SELECT * FROM person LIMIT 15;

SELECT * FROM person OFFSET 5;

SELECT * FROM person OFFSET 5 LIMIT 15;

SELECT * FROM person WHERE gender = 'Female' OFFSET 5 LIMIT 15;

SELECT * FROM person FETCH FIRST 8 ROWS ONLY;

SELECT * FROM person OFFSET 5 FETCH FIRST 8 ROWS ONLY;

SELECT * FROM person OFFSET 5 FETCH FIRST ROW ONLY;
